import { defineTable } from 'convex/server';
import { v } from 'convex/values';

export const attachmentsTable = defineTable({
  messageId: v.id('messages'),
  userId: v.id('users'),
  uploaded: v.boolean(), // Whether the attachment was uploaded by user or generated by AI
  fileId: v.id('_storage'),
  fileName: v.string(),
  fileType: v.string(),
  fileSize: v.number(),
  deleteTime: v.optional(v.number()),
})
  .index('by_message', ['messageId'])
  .index('by_user', ['userId'])
  .index('by_uploaded', ['uploaded'])
  .index('by_delete_time', ['deleteTime']);
